version: "1.0"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4840:4840"
    volumes:
      - ./backend:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres:user123@db:5432/postgres
    depends_on:
      - db
    command: ["bun", "dev"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - backend
    command: ["bun", "dev", "--host"]

  db:
    image: postgres:17.4-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata:
